name: Selfcare Oasis
favicon: null
layout_spectrum: 0.006302394438534975
typography_spectrum: 0.1549815887119621
title: Why Come Here
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4ec3bd'
    - '#6b5035'
    - '#000000'
    - '#fcfeff'
    - '#f77a00'
  brandStrength: 0.7368112683761865
  lightness: 0.6105720524210483
  saturation: 0.0630712821148336
  rhythmicContrast: 0.5492367714177817
purpose: []
